(function(){
  'use strict';
  const C=PartnerCore,A=PartnerAPI,$=id=>document.getElementById(id),esc=C.esc;
  const query=new URLSearchParams(location.search);
  let data=null,sha='',config=A.settings(),projects=[],versions={},selected=query.get('partner')||'',project=query.get('project')||'',mode=project?'projects':'people',loading=false;
  const stages=['线索获取','前期信息提供','引荐对接','关系协调','团队分工','招标准备与参与','履约协调'];
  $('partnerOwner').value=config.owner;$('partnerRepo').value=config.repo;$('partnerBranch').value=config.branch;$('partnerToken').value=config.token;
  function status(text){$('partnerStatus').textContent=text;}
  function setMode(next){mode=next;$('peopleView').hidden=mode!=='people';$('projectsView').hidden=mode!=='projects';$('showPeople').setAttribute('aria-pressed',String(mode==='people'));$('showProjects').setAttribute('aria-pressed',String(mode==='projects'));updateUrl();}
  function updateUrl(){const url=new URL(location.href);url.searchParams.delete('partner');url.searchParams.delete('project');if(mode==='projects'&&project)url.searchParams.set('project',project);else if(selected)url.searchParams.set('partner',selected);history.replaceState(null,'',url);}
  function currentConfig(){const previous=A.settings();const next={...previous,owner:$('partnerOwner').value.trim(),repo:$('partnerRepo').value.trim(),branch:$('partnerBranch').value.trim()||'main',token:$('partnerToken').value.trim()};if(!next.owner||!next.repo)throw Error('请填写仓库连接设置');return next;}
  function saveSettings(){let common={};try{common=JSON.parse(localStorage.getItem('bd-weekly-github-settings')||'{}');}catch(_){}localStorage.setItem('bd-weekly-github-settings',JSON.stringify({...common,token:config.token}));localStorage.setItem('bd-partner-settings',JSON.stringify({owner:config.owner,repo:config.repo,branch:config.branch}));}
  function sourceUrl(p){return 'https://github.com/'+encodeURIComponent(config.owner)+'/'+encodeURIComponent(config.repo)+'/blob/'+encodeURIComponent(config.branch)+'/'+encodeURIComponent(p.source_file);}
  function stale(p){return !versions[p.source_file]||versions[p.source_file]!==p.source_sha;}
  function warning(p){return stale(p)?'<div class="partner-warning">档案正文已变化或版本无法核对。以下评价与关系图为上次整理结果，请先查看最新正文，再让建档助手更新可视化索引。</div>':'';}
  function renderList(){if(!data)return;const term=$('partnerSearch').value.trim().toLowerCase();const list=data.partners.filter(p=>(p.id+' '+p.role+' '+p.summary).toLowerCase().includes(term));$('partnerList').innerHTML=list.map(p=>`<button class="partner-select" type="button" data-partner="${esc(p.id)}" aria-pressed="${p.id===selected}"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small><span>${C.counts(p)[0]} 个已记录项目 · ${stale(p)?'评价待同步':'档案版本一致'}</span></button>`).join('')||'<p class="partner-empty">没有匹配的伙伴。</p>';}
  function paths(p,projectId){const relations=(p.relations||[]).filter(r=>!projectId||(r.project_ids||[]).includes(projectId));return relations.map(r=>`<div class="relation-path"><span class="relation-node">${esc(r.from)}</span><span class="relation-edge ${r.evidence==='claim'?'claim':''}">${esc(r.label)}<small>${esc(r.distance)} · ${r.evidence==='claim'?'自述 / 转述待核':r.evidence==='observed'?'用户亲历':'用户陈述'}</small></span><span class="relation-node">${esc(r.to)}</span></div>`).join('')||'<p class="partner-caption">该项目尚未整理关系路径，关联不代表这些资源已用于此项目。</p>';}
  function renderDetail(){if(!data)return;const p=data.partners.find(p=>p.id===selected)||data.partners[0];if(!p)return;selected=p.id;const count=C.counts(p);
    $('partnerDetail').innerHTML=`<header class="partner-detail-header"><div><h2>${esc(p.name)}</h2><span class="partner-role">${esc(p.role)}</span></div><button type="button" data-add="${esc(p.id)}">关联项目</button></header><p class="partner-summary">${esc(p.summary)}</p>${warning(p)}<div class="partner-metrics">${C.STAGES.map((s,i)=>`<div class="partner-metric"><b>${count[i]}</b><span>${s}</span></div>`).join('')}</div><p class="partner-caption">累计已记录项目，按项目编号去重；零表示暂无对应记录。已落实合作不等同于项目中标，平台会面不自动计作项目。</p>
    <section class="partner-section"><h3>01 · 项目接触与转化</h3><div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>关联项目</th><th>已达到阶段 / 当前状态</th><th>角色与依据</th><th>操作</th></tr></thead><tbody>${p.project_links.map(l=>`<tr><td><a href="${esc(C.href('ledger.html',{project:l.project_id}))}">${esc(projects.find(x=>x.project_id===l.project_id)?.['项目名称']||l.project_name)} ↗</a></td><td>${C.STAGES[l.stage]}<br>${esc(l.status)}</td><td>${esc(l.role)}<br><small>${esc(l.evidence)}</small></td><td><button data-edit="${esc(l.project_id)}" type="button">编辑关联</button><br><a href="${esc(C.href('partners.html',{project:l.project_id}))}">关系 / 对比</a></td></tr>`).join('')||'<tr><td colspan="4">暂无项目关联</td></tr>'}</tbody></table></div></section>
    <div class="partner-dimensions">${p.dimensions.map((d,i)=>`<section class="partner-dimension"><h3>0${i+2} · ${esc(d.label)}</h3><p>${esc(d.text)}</p></section>`).join('')}</div>
    <section class="partner-section"><h3>关系路径</h3><p class="partner-caption">实线：档案记录的经历或安排；虚线：自述或转述待核。均保留来源，不代表独立外部核验。</p>${paths(p)}</section>
    <section class="partner-section"><h3>承诺与行动</h3><div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>事项</th><th>状态</th><th>依据</th></tr></thead><tbody>${p.commitments.map(c=>`<tr><td>${esc(c.text)}</td><td>${esc(c.status)}</td><td>${esc(c.source)}</td></tr>`).join('')}</tbody></table></div></section>
    <section class="partner-section"><h3>组织推进覆盖</h3><div class="partner-stage-track">${stages.map(s=>`<span class="${p.coverage.includes(s)?'recorded':''}">${esc(s)} · ${p.coverage.includes(s)?'有行为记录':'暂无记录'}</span>`).join('')}</div><p class="partner-caption">有行为记录不等于能够独立完成该环节或保证项目结果。</p></section>
    <details id="sourceDetails"><summary>查看最新档案正文</summary><p><a href="${esc(sourceUrl(p))}" target="_blank" rel="noopener">在 GitHub 查看主档 ↗</a></p><p id="sourceVersion" class="partner-caption"></p><pre id="sourceText" class="partner-source">展开后读取正文。</pre></details>`;
    $('sourceDetails').addEventListener('toggle',async()=>{if(!$('sourceDetails')?.open)return;const id=p.id;try{const r=await A.read(config,p.source_file);if(selected!==id)return;$('sourceText').textContent=r.text.replace(/WPW/g,'PWW').replace(/FLX/g,'FXL');$('sourceVersion').textContent='本次正文版本 '+r.sha.slice(0,10)+' · '+new Date().toLocaleString('zh-CN');}catch(e){if(selected===id)$('sourceText').textContent=e.message;}});
    renderList();updateUrl();
  }
  function allProjects(){const combined=new Map(projects.map(p=>[p.project_id,{id:p.project_id,name:p['项目名称']||p.project_id}]));for(const p of data?.partners||[])for(const l of p.project_links)if(!combined.has(l.project_id))combined.set(l.project_id,{id:l.project_id,name:l.project_name+'（台账未返回）'});return [...combined.values()];}
  function fillProjects(){const list=allProjects();$('relationProject').innerHTML='<option value="">选择项目查看关系</option>'+list.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(project&&!list.some(p=>p.id===project)){status('指定项目在当前台账中不存在，请重新选择。');project='';}$('relationProject').value=project;}
  function renderProject(){if(!data)return;$('backToLedger').href=C.href('ledger.html',project?{project}:{});if(!project){$('projectRelations').innerHTML='<p class="partner-empty">选择一个项目，查看关联伙伴的关系图与合作对比。</p>';return;}
    const rows=C.forProject(data,project),title=allProjects().find(p=>p.id===project)?.name||project;
    $('projectRelations').innerHTML=`<div class="project-root">${esc(title)}</div>${rows.length?`<div class="project-branches">${rows.map(({partner:p,link:l})=>`<article class="project-branch"><header><strong><a href="${esc(C.href('partners.html',{partner:p.id}))}">${esc(p.name)} ↗</a></strong><span>${esc(l.status)} · ${esc(l.role)}</span></header>${warning(p)}${paths(p,project)}<p>下一步验证：${esc(l.next||'尚未填写')}</p></article>`).join('')}</div><h2>合作关系对比</h2><p class="partner-caption">项目角色与合作状态来自关联记录；能力评价来自伙伴主档，不能直接视作本项目的已兑现能力。</p><div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>伙伴 / 状态</th><th>关系能力</th><th>履约记录</th><th>组织推进</th><th>合作条件与协同</th><th>下一步验证</th></tr></thead><tbody>${rows.map(({partner:p,link:l})=>`<tr><td><a href="${esc(C.href('partners.html',{partner:p.id}))}">${esc(p.id)}</a><br>${esc(l.status)}${stale(p)?'<br>评价待同步':''}</td><td>${esc(p.dimensions[0].text)}</td><td>${esc(p.dimensions[1].text)}</td><td>${esc(p.dimensions[2].text)}</td><td>${esc(p.dimensions[4].text)}<br>${esc(p.dimensions[5].text)}</td><td>${esc(l.next)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="partner-empty">此项目还没有关联伙伴。点击“关联伙伴”建立关系。</p>'}`;
    updateUrl();
  }
  async function load(){if(loading)return;loading=true;$('refreshPartners').disabled=true;status('正在读取伙伴档案与项目台账…');try{config=currentConfig();saveSettings();const index=await A.readIndex(config);data=index.data;sha=index.sha;const results=await Promise.allSettled([A.sourceVersions(config),A.read({...config,owner:config.ledgerOwner,repo:config.ledgerRepo,branch:config.ledgerBranch},'ledger/market_workbench_snapshot.json')]);versions=results[0].status==='fulfilled'?results[0].value:{};projects=[];let note='';if(results[1].status==='fulfilled'){const snapshot=JSON.parse(results[1].value.text);projects=(snapshot.projects||[]).filter(p=>!['已删除','已合并','已归档'].includes(p['记录状态']));}else note='；项目台账读取失败，保留已存关联，新增关联暂不可用。'+results[1].reason.message;fillProjects();renderDetail();renderProject();setMode(mode);status(`已读取 ${data.partners.length} 位伙伴 · ${projects.length} 个台账项目 · 关联版本 ${sha.slice(0,8)} · ${new Date().toLocaleTimeString('zh-CN')}${note}`);$('partnerSettings').open=false;}catch(e){status(e.message);$('partnerSettings').open=true;}finally{loading=false;$('refreshPartners').disabled=false;}}
  function setFormLink(){const p=data.partners.find(p=>p.id===$('linkPartner').value);const l=p?.project_links.find(l=>l.project_id===$('linkProject').value);$('linkStage').value=String(l?.stage??0);$('linkStatus').value=l?.status||'';$('linkRole').value=l?.role||'';$('linkEvidence').value=l?.evidence||'';$('linkNext').value=l?.next||'';}
  function openLink(partnerId,projectId){if(!data)return;if(!projects.length){status('请先成功读取项目台账，再建立或修改关联。');return;}$('linkPartner').innerHTML=data.partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('linkProject').innerHTML=projects.map(p=>`<option value="${esc(p.project_id)}">${esc(p['项目名称'])}</option>`).join('');if(partnerId)$('linkPartner').value=partnerId;if(projectId)$('linkProject').value=projectId;setFormLink();$('linkResult').textContent='';$('linkDialog').showModal();}
  $('refreshPartners').addEventListener('click',load);$('showPeople').addEventListener('click',()=>setMode('people'));$('showProjects').addEventListener('click',()=>setMode('projects'));$('partnerSearch').addEventListener('input',renderList);
  $('partnerList').addEventListener('click',e=>{const button=e.target.closest('[data-partner]');if(button){selected=button.dataset.partner;renderDetail();}});
  $('partnerDetail').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),edit=e.target.closest('[data-edit]');if(add)openLink(add.dataset.add,project);if(edit)openLink(selected,edit.dataset.edit);});
  $('relationProject').addEventListener('change',()=>{project=$('relationProject').value;renderProject();});$('addProjectPartner').addEventListener('click',()=>openLink('',project));$('closeLink').addEventListener('click',()=>$('linkDialog').close());$('linkPartner').addEventListener('change',setFormLink);$('linkProject').addEventListener('change',setFormLink);
  $('linkForm').addEventListener('submit',async e=>{e.preventDefault();$('saveLink').disabled=true;try{const id=$('linkProject').value,p=projects.find(p=>p.project_id===id);if(!p)throw Error('请选择有效台账项目');const next=C.upsertLink(data,$('linkPartner').value,{project_id:id,project_name:p['项目名称'],stage:Number($('linkStage').value),status:$('linkStatus').value.trim(),role:$('linkRole').value.trim(),evidence:$('linkEvidence').value.trim(),next:$('linkNext').value.trim()});const saved=await A.saveIndex(config,next,sha);data=next;sha=saved.sha;fillProjects();renderDetail();renderProject();$('linkDialog').close();status('关联已保存到 GitHub · 提交 '+saved.commit.slice(0,8)+'。台账刷新后可查看伙伴入口。');}catch(err){$('linkResult').textContent=err.message;}finally{$('saveLink').disabled=false;}});
  setMode(mode);if(config.token)load();else $('partnerSettings').open=true;
})();
