(function(){
'use strict';
window.PartnerBoard={mount(host,{projectId,title,partners,stored,save,onChange=()=>{}}){
 const esc=PartnerCore.esc,key='partner-board-draft:'+projectId;let board=JSON.parse(JSON.stringify(stored||{nodes:[],edges:[]})),dirty=false,selected='',zoom=1,camera={x:0,y:0};
 try{const draft=JSON.parse(localStorage.getItem(key)||'null');if(draft){board=draft;dirty=true;}}catch(_){}
 board.nodes=board.nodes.filter(n=>!(n.id==='project'&&n.type==='项目'&&!board.edges.some(e=>e.from===n.id||e.to===n.id)));
 board.schema_version=5;board.project_id=projectId;board.title=title;
 for(const n of board.nodes){if(!['建设方','主管部门','分管部门','使用方','招标代理','合作方',''].includes(n.type)){n.legacy_type=n.type;n.type='';}if(n.type!=='合作方'){if(n.department){n.note=(n.note?n.note+'\n':'')+'原部门：'+n.department;}delete n.department;n.person??='';n.position??='';}}
 for(const e of board.edges){e.kind??='关系线';e.chain??='';e.evidence??='';if(!['strong','weak','pending'].includes(e.line_style))e.line_style=e.strength==='strong'?'strong':e.verification==='已验证'?'weak':'pending';e.strength=e.line_style;e.distance??='直接';e.shape=e.shape==='curve'?'curve':'straight';}
 const uid=()=>crypto.randomUUID(),nodeOptions=()=>board.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('');
 host.innerHTML=`<section class="relationship-board"><h2>${esc(title)}</h2><p class="board-subtitle">项目决策链条</p><p class="partner-caption">点击新增节点，或双击空白处创建；双击卡片文字直接编辑，点击卡片在画布内编辑属性；滚轮缩放、按住中键拖动画布，Delete 删除选中项。从节点圆点拖向另一个节点连线，点击线选择线型及直线／曲线；双击连线后拖动两个控制点调整曲率。画布可向任意方向持续平移。</p><div class="board-toolbar"><button data-b="add" type="button">＋ 新增节点</button><select data-b="partner" aria-label="选择导入伙伴">${partners.map(p=>`<option value="${esc(p.id)}">${esc(p.id)}</option>`).join('')}</select><button data-b="import" type="button">导入合作方</button><button data-b="minus" type="button">缩小</button><button data-b="plus" type="button">放大</button><button data-b="fit" type="button">显示全部</button><button data-b="save" type="button">保存白板</button><span data-b="status" role="status"></span></div><div class="board-line-legend"><span>═ 强关联</span><span>─ 弱关联</span><span>┄ 待核验</span></div><div class="board-layout board-direct" tabindex="0"><div class="board-scroll"><svg data-b="canvas" width="100%" height="100%" aria-label="项目关系白板"></svg></div><div class="board-floating-editor" hidden><button type="button" data-b="closeEditor" aria-label="关闭编辑">×</button><form data-b="nodeForm"><h3>决策节点 / 合作方</h3><label>类型<select data-b="type"><option value="">待确认</option><option>建设方</option><option>主管部门</option><option>分管部门</option><option>使用方</option><option>招标代理</option><option>合作方</option></select></label><label>节点简称 / 合作方代号<input data-b="name" required maxlength="100"></label><div data-b="decisionFields"><label>人员<input data-b="person" placeholder="姓名不明确可填待确认"></label><label>职务<input data-b="position" placeholder="如：院长、分管副区长"></label></div><label>职责、权限与依据<textarea data-b="note" rows="3"></textarea></label><button data-b="deleteNode" type="button">删除节点</button></form><form data-b="edgeForm"><h3>链条 / 关系连线</h3><label>所属决策链条<input data-b="chain" list="decisionChainNames" placeholder="如：院方决策线、区政府审批线"></label><datalist id="decisionChainNames"></datalist><label>关系说明<input data-b="label" required placeholder="如：汇报、分管、直接联系"></label><label>关系核验<select data-b="verification"><option>待验证</option><option>已验证</option><option>存疑</option></select></label><label>直接 / 间接<select data-b="distance"><option>直接</option><option>间接</option></select></label><label>依据 / 存疑原因<textarea data-b="evidence" rows="2"></textarea></label><label>连线形状<select data-b="shape"><option value="straight">直线</option><option value="curve">曲线</option></select></label><p>双击连线，拖动两个控制点调整曲率。</p><label>线型<select data-b="strength"><option value="strong">强关联 · 双粗线</option><option value="weak">弱关联 · 单细线</option><option value="pending">待核验 · 虚线</option></select></label><button data-b="deleteEdge" type="button">删除连线</button></form><p data-b="hint">点击节点编辑属性；从节点圆点拖到另一个节点即可连线。点击线编辑线型。</p></div></div></section>`;
 const $=s=>host.querySelector(`[data-b="${s}"]`),status=t=>$('status').textContent=t;
 const layout=host.querySelector('.board-layout'),viewport=host.querySelector('.board-scroll'),editor=host.querySelector('.board-floating-editor');
 function showEditor(n){editor.hidden=!n;if(!n)return;const left=(n.x-camera.x)*zoom+250*zoom,top=(n.y-camera.y)*zoom;editor.style.left=Math.max(8,Math.min(layout.clientWidth-300,left))+'px';editor.style.top=Math.max(8,Math.min(220,top))+'px';}
 $('closeEditor').onclick=()=>{editor.hidden=true;layout.focus({preventScroll:true});};
 layout.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'){editor.hidden=true;return;}if(e.key==='Delete'){if(!selected&&!editingEdge)return;e.preventDefault();if(selected)$('deleteNode').click();else $('deleteEdge').click();layout.focus({preventScroll:true});}});
 function markSelection(){refreshControls();for(const el of host.querySelectorAll('[data-node],[data-edge]'))el.classList.toggle('board-selected',el.dataset.node===selected||el.dataset.edge===editingEdge);}
 function changed(){onChange(JSON.parse(JSON.stringify(board)));board.view={x:camera.x,y:camera.y,zoom};dirty=true;try{localStorage.setItem(key,JSON.stringify(board));status('未保存 · 本机草稿已保留');}catch(_){status('未保存 · 请保存白板');}}
 function pick(id){selected=id;showEditor(id?board.nodes.find(n=>n.id===id):null);editingEdge='';$('nodeForm').hidden=!id;$('edgeForm').hidden=true;$('hint').hidden=!!id;const n=board.nodes.find(n=>n.id===id);$('name').value=n?.name||'';$('type').value=['建设方','主管部门','分管部门','使用方','招标代理','合作方'].includes(n?.type)?n.type:'';$('note').value=n?.note||'';for(const k of ['person','position'])$(k).value=n?.[k]||'';$('decisionFields').hidden=$('type').value==='合作方';markSelection();}
 function edgeGeometry(e,a,b){
   const ac={x:a.x+120,y:a.y+64},bc={x:b.x+120,y:b.y+64},dx=bc.x-ac.x,dy=bc.y-ac.y,len=Math.hypot(dx,dy)||1;
   const cp=e.controls||[{x:dx/3-dy/len*80,y:dy/3+dx/len*80},{x:-dx/3-dy/len*80,y:-dy/3+dx/len*80}];
   const c1={x:ac.x+cp[0].x,y:ac.y+cp[0].y},c2={x:bc.x+cp[1].x,y:bc.y+cp[1].y};
   const boundary=(center,toward)=>{const vx=toward.x-center.x,vy=toward.y-center.y,scale=1/Math.max(Math.abs(vx)/124,Math.abs(vy)/68,.001);return {x:center.x+vx*scale,y:center.y+vy*scale};};
   const curved=e.shape==='curve',start=boundary(ac,curved?c1:bc),end=boundary(bc,curved?c2:ac);
   const at=t=>{const u=1-t;return curved?{x:u*u*u*start.x+3*u*u*t*c1.x+3*u*t*t*c2.x+t*t*t*end.x,y:u*u*u*start.y+3*u*u*t*c1.y+3*u*t*t*c2.y+t*t*t*end.y}:{x:start.x+(end.x-start.x)*t,y:start.y+(end.y-start.y)*t};};
   const path=offset=>{if(!offset)return curved?`M${start.x},${start.y} C${c1.x},${c1.y} ${c2.x},${c2.y} ${end.x},${end.y}`:`M${start.x},${start.y} L${end.x},${end.y}`;return Array.from({length:65},(_,i)=>{const t=i/64,u=1-t,p=at(t),vx=curved?3*u*u*(c1.x-start.x)+6*u*t*(c2.x-c1.x)+3*t*t*(end.x-c2.x):end.x-start.x,vy=curved?3*u*u*(c1.y-start.y)+6*u*t*(c2.y-c1.y)+3*t*t*(end.y-c2.y):end.y-start.y,l=Math.hypot(vx,vy)||1;return `${i?'L':'M'}${p.x-vy/l*offset},${p.y+vx/l*offset}`;}).join(' ');};
   return {start,end,c1,c2,mid:at(.5),path,controls:cp};
 }
 function curveControls(){const e=board.edges.find(x=>x.id===editingEdge&&x.shape==='curve');if(!e)return '';const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to);if(!a||!b)return '';const g=edgeGeometry(e,a,b);return `<g class="curve-controls"><path d="M${g.start.x},${g.start.y} L${g.c1.x},${g.c1.y} M${g.end.x},${g.end.y} L${g.c2.x},${g.c2.y}" stroke="#7595aa" stroke-dasharray="4 4" fill="none" pointer-events="none"/>${[g.c1,g.c2].map((p,i)=>`<circle data-curve-edge="${esc(e.id)}" data-control="${i}" cx="${p.x}" cy="${p.y}" r="${8/zoom}" fill="white" stroke="#245f87" stroke-width="${2/zoom}"><title>拖动调整曲率 ${i+1}</title></circle>`).join('')}</g>`;}
 function refreshControls(){const svg=$('canvas');svg.querySelector('.curve-controls')?.remove();svg.insertAdjacentHTML('beforeend',curveControls());}
 function draw(){const byId=new Map(board.nodes.map(n=>[n.id,n]));$('canvas').innerHTML=`<defs><marker id="board-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#5e7b8b"/></marker></defs>`+board.edges.map(e=>{const a=byId.get(e.from),b=byId.get(e.to);if(!a||!b)return '';const g=edgeGeometry(e,a,b),style=e.line_style||'pending',label={strong:'强关联',weak:'弱关联',pending:'待核验'}[style];const stroke=(offset,width)=>`<path class="board-visible-edge" d="${g.path(offset)}" stroke="#466879" stroke-width="${width}" fill="none" ${style==='pending'?'stroke-dasharray="7 5"':''}/>`;return `<g data-edge="${esc(e.id)}"><title>${esc(e.label)} · ${label}</title><path class="board-edge-hit" d="${g.path(0)}" stroke="transparent" stroke-width="20" fill="none"/>${style==='strong'?stroke(-3.5,3)+stroke(3.5,3):stroke(0,1.5)}<text x="${g.mid.x}" y="${g.mid.y-12}" text-anchor="middle" class="board-line-label">${esc((e.chain?e.chain+' · ':'')+e.label.slice(0,20))}</text></g>`;}).join('')+board.nodes.map(n=>`<g data-node="${esc(n.id)}" transform="translate(${n.x},${n.y})" tabindex="0" role="button" aria-label="编辑${esc(n.name)}"><title>${esc(n.name)}：${esc(n.note)}</title><rect width="240" height="128" rx="9" fill="${n.type==='合作方'?'#e0eee7':'#fff'}" stroke="#8fa9b8"/><text x="12" y="23" class="board-node-type">${esc(n.type||'类型待确认')}</text><text data-edit-field="name" x="12" y="47">${esc(n.name.slice(0,16))}</text>${n.type==='合作方'?`<text x="12" y="76">背景：${esc((partners.find(p=>p.id===(n.partner_id||n.name))?.role_platform?.name||'待确认').slice(0,14))}</text>`:`<text data-edit-field="person" x="12" y="76">人员：${esc((n.person||'待确认').slice(0,15))}</text><text data-edit-field="position" x="12" y="103">职务：${esc((n.position||'待确认').slice(0,15))}</text>`}${[[0,64],[240,64],[120,0],[120,128]].map(([x,y])=>`<circle data-port="${esc(n.id)}" cx="${x}" cy="${y}" r="7" fill="#fff" stroke="#355d85" stroke-width="2"/>`).join('')}</g>`).join('');
 markSelection();host.querySelector('#decisionChainNames').innerHTML=[...new Set(board.edges.map(e=>e.chain).filter(Boolean))].map(c=>`<option value="${esc(c)}">`).join('');
 }
 let editingEdge='',drag=null,linking=null,pan=null,controlDrag=null;
 function pickEdge(id){selected='';editingEdge=id;const item=board.edges.find(e=>e.id===id);const a=board.nodes.find(n=>n.id===item.from),b=board.nodes.find(n=>n.id===item.to);showEditor({x:(a.x+b.x)/2,y:(a.y+b.y)/2});const edge=board.edges.find(e=>e.id===id);$('nodeForm').hidden=true;$('edgeForm').hidden=false;$('hint').hidden=true;for(const k of ['label','chain','evidence','strength','verification','distance','shape'])$(k).value=edge[k]||'';markSelection();}
 function addNode(x,y){const n={id:uid(),name:'新节点',type:'建设方',person:'',position:'',note:'',x:x??camera.x+(80+(board.nodes.length%3)*280)/zoom,y:y??camera.y+100/zoom};board.nodes.push(n);changed();draw();pick(n.id);$('name').focus();$('name').select();}
 $('add').onclick=()=>addNode();
 $('nodeForm').onsubmit=e=>e.preventDefault();$('edgeForm').onsubmit=e=>e.preventDefault();
 for(const k of ['name','type','person','position','note'])$(k).addEventListener('input',()=>{const n=board.nodes.find(n=>n.id===selected);if(!n)return;n[k]=$(k).value;$('decisionFields').hidden=n.type==='合作方';changed();draw();});
 for(const k of ['label','chain','evidence','strength','verification','distance','shape'])$(k).addEventListener('input',()=>{const e=board.edges.find(e=>e.id===editingEdge);if(!e)return;e[k]=$(k).value;if(k==='strength')e.line_style=e.strength;changed();draw();});
 $('deleteNode').onclick=()=>{board.nodes=board.nodes.filter(n=>n.id!==selected);board.edges=board.edges.filter(e=>e.from!==selected&&e.to!==selected);changed();draw();pick('');};
 $('deleteEdge').onclick=()=>{board.edges=board.edges.filter(e=>e.id!==editingEdge);changed();draw();pick('');};
 const svg=$('canvas'),point=e=>{const r=svg.getBoundingClientRect();return {x:camera.x+(e.clientX-r.left)/zoom,y:camera.y+(e.clientY-r.top)/zoom};};
 svg.onpointerdown=e=>{if(e.button===1){e.preventDefault();editor.hidden=true;pan={x:e.clientX,y:e.clientY,left:camera.x,top:camera.y};svg.setPointerCapture(e.pointerId);viewport.classList.add('board-panning');return;}if(e.button!==0)return;e.preventDefault();layout.focus({preventScroll:true});const control=e.target.closest('[data-control]');if(control){controlDrag={edge:control.dataset.curveEdge,index:Number(control.dataset.control)};editor.hidden=true;svg.setPointerCapture(e.pointerId);return;}const port=e.target.closest('[data-port]');if(port){e.preventDefault();linking={from:port.dataset.port,start:point(e)};svg.setPointerCapture(e.pointerId);return;}const edge=e.target.closest('[data-edge]');if(edge){pickEdge(edge.dataset.edge);return;}const g=e.target.closest('[data-node]');if(!g){pick('');return;}const n=board.nodes.find(n=>n.id===g.dataset.node);pick(n.id);drag={id:n.id,x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};};
 svg.onpointermove=e=>{if(controlDrag){const edge=board.edges.find(x=>x.id===controlDrag.edge),a=board.nodes.find(n=>n.id===edge.from),b=board.nodes.find(n=>n.id===edge.to),g=edgeGeometry(edge,a,b),q=point(e),anchor=controlDrag.index===0?a:b;edge.controls=g.controls.map(p=>({...p}));edge.controls[controlDrag.index]={x:q.x-anchor.x-120,y:q.y-anchor.y-64};draw();return;}if(pan){camera.x=pan.left+(pan.x-e.clientX)/zoom;camera.y=pan.top+(pan.y-e.clientY)/zoom;applyView();return;}if(linking){svg.querySelector('[data-preview]')?.remove();const q=point(e);svg.insertAdjacentHTML('beforeend',`<path data-preview d="M${linking.start.x},${linking.start.y} L${q.x},${q.y}" stroke="#355d85" stroke-width="2" stroke-dasharray="7 5" pointer-events="none"/>`);return;}if(!drag)return;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)<3)return;svg.setPointerCapture(e.pointerId);const n=board.nodes.find(n=>n.id===drag.id);n.x=drag.nx+(e.clientX-drag.x)/zoom;n.y=drag.ny+(e.clientY-drag.y)/zoom;draw();};
 svg.onpointerup=e=>{if(controlDrag){controlDrag=null;changed();layout.focus({preventScroll:true});return;}if(pan){pan=null;viewport.classList.remove('board-panning');return;}if(linking){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]'),from=linking.from,to=target?.dataset.node;linking=null;svg.querySelector('[data-preview]')?.remove();if(to&&to!==from){const hasPartner=[from,to].some(id=>board.nodes.find(n=>n.id===id)?.type==='合作方');const edge={id:uid(),from,to,kind:hasPartner?'合作方关系':'决策链条',chain:'',label:'待补充关系',verification:'待验证',distance:'直接',strength:'pending',line_style:'pending',evidence:''};board.edges.push(edge);changed();draw();pickEdge(edge.id);}return;}if(drag){changed();drag=null;layout.focus({preventScroll:true});}};
 svg.onpointercancel=()=>{if(controlDrag){controlDrag=null;changed();}pan=null;viewport.classList.remove('board-panning');linking=null;drag=null;svg.querySelector('[data-preview]')?.remove();};
 svg.onauxclick=e=>{if(e.button===1)e.preventDefault();};svg.addEventListener('mousedown',e=>{if(e.button===1)e.preventDefault();});
 svg.ondblclick=e=>{const line=e.target.closest('[data-edge]');if(line){pickEdge(line.dataset.edge);const edge=board.edges.find(x=>x.id===editingEdge);edge.shape='curve';$('shape').value='curve';editor.hidden=true;changed();draw();return;}if(e.target.closest('[data-control]'))return;const g=e.target.closest('[data-node]');if(!g){if(!e.target.closest('[data-edge]')){const q=point(e);addNode(q.x,q.y);}return;}const n=board.nodes.find(n=>n.id===g.dataset.node),field=e.target.dataset.editField||'name';pick(n.id);editor.hidden=true;const overlay=document.createElementNS('http://www.w3.org/2000/svg','foreignObject');overlay.setAttribute('x',n.x+8);overlay.setAttribute('y',n.y+25);overlay.setAttribute('width','224');overlay.setAttribute('height','40');const input=document.createElement('input');input.value=n[field]||'';input.setAttribute('aria-label','直接编辑'+field);overlay.appendChild(input);svg.appendChild(overlay);input.onpointerdown=e=>e.stopPropagation();input.oninput=()=>{n[field]=input.value;$(field).value=input.value;changed();};input.onblur=()=>draw();input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();input.blur();}};input.focus();input.select();};
 svg.onkeydown=e=>{const g=e.target.closest('[data-node]');if(g&&e.key==='Enter'){pick(g.dataset.node);$('name').focus();}};
 function applyView(){svg.setAttribute('viewBox',`${camera.x} ${camera.y} ${viewport.clientWidth/zoom} ${viewport.clientHeight/zoom}`);viewport.style.backgroundSize=`${20*zoom}px ${20*zoom}px`;viewport.style.backgroundPosition=`${-camera.x*zoom}px ${-camera.y*zoom}px`;refreshControls();}
 function setZoom(next,clientX,clientY){const r=svg.getBoundingClientRect(),x=clientX-r.left,y=clientY-r.top,worldX=camera.x+x/zoom,worldY=camera.y+y/zoom;zoom=Math.max(.1,Math.min(3,next));camera.x=worldX-x/zoom;camera.y=worldY-y/zoom;applyView();editor.hidden=true;}
 function fit(){if(!board.nodes.length){camera={x:0,y:0};zoom=1;}else{const points=board.edges.filter(e=>e.shape==='curve').flatMap(e=>{const a=board.nodes.find(n=>n.id===e.from),b=board.nodes.find(n=>n.id===e.to);if(!a||!b)return [];const g=edgeGeometry(e,a,b);return [g.c1,g.c2];});const minX=Math.min(...board.nodes.map(n=>n.x),...points.map(p=>p.x))-60,minY=Math.min(...board.nodes.map(n=>n.y),...points.map(p=>p.y))-60,maxX=Math.max(...board.nodes.map(n=>n.x+240),...points.map(p=>p.x))+60,maxY=Math.max(...board.nodes.map(n=>n.y+128),...points.map(p=>p.y))+60;zoom=Math.max(.01,Math.min(1.5,viewport.clientWidth/(maxX-minX),viewport.clientHeight/(maxY-minY)));camera={x:minX-(viewport.clientWidth/zoom-(maxX-minX))/2,y:minY-(viewport.clientHeight/zoom-(maxY-minY))/2};}editor.hidden=true;applyView();}
 $('fit').onclick=fit;
 const resizeObserver=new ResizeObserver(()=>{if(!host.isConnected){resizeObserver.disconnect();return;}applyView();});resizeObserver.observe(viewport);
 viewport.addEventListener('wheel',e=>{e.preventDefault();if(drag||linking||pan||controlDrag)return;const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?viewport.clientHeight:1);setZoom(zoom*Math.exp(-Math.max(-240,Math.min(240,delta))*.002),e.clientX,e.clientY);},{passive:false});
 for(const [id,delta] of [['minus',-.15],['plus',.15]])$(id).onclick=()=>{const rect=viewport.getBoundingClientRect();setZoom(zoom+delta,rect.left+viewport.clientWidth/2,rect.top+viewport.clientHeight/2);};
 $('import').onclick=()=>{const p=partners.find(p=>p.id===$('partner').value);if(!p)return;let n=board.nodes.find(n=>n.partner_id===p.id||(n.type==='合作方'&&n.name===p.id));if(!n){n={id:uid(),partner_id:p.id,name:p.id,type:'合作方',person:'',position:'',note:'',x:camera.x+120/zoom,y:camera.y+120/zoom};board.nodes.push(n);changed();draw();}pick(n.id);};
 $('save').onclick=async()=>{$('save').disabled=true;board.view={x:camera.x,y:camera.y,zoom};const snapshot=JSON.parse(JSON.stringify(board));status('正在保存…');try{await save(snapshot);if(JSON.stringify(board)===JSON.stringify(snapshot)){dirty=false;localStorage.removeItem(key);status('白板已保存');}else status('已保存，另有新的修改待保存');}catch(e){status(e.message+'；当前草稿已保留');}finally{$('save').disabled=false;}};
 if(board.view&&[board.view.x,board.view.y,board.view.zoom].every(Number.isFinite)&&board.view.zoom>0){camera={x:board.view.x,y:board.view.y};zoom=board.view.zoom;applyView();}else fit();
 onChange(JSON.parse(JSON.stringify(board)));draw();pick('');status(dirty?'已恢复未保存的本机草稿':'拖动节点或导入伙伴开始整理');
}};
})();
