(function(){
'use strict';
window.PartnerBoard={mount(host,{projectId,title,partners,stored,save}){
 const esc=PartnerCore.esc,key='partner-board-draft:'+projectId;let board=JSON.parse(JSON.stringify(stored||{nodes:[],edges:[]})),dirty=false,selected='',zoom=1;
 try{const draft=JSON.parse(localStorage.getItem(key)||'null');if(draft){board=draft;dirty=true;}}catch(_){}
 board.nodes=board.nodes.filter(n=>!(n.id==='project'&&n.type==='项目'&&!board.edges.some(e=>e.from===n.id||e.to===n.id)));
 board.schema_version=3;board.project_id=projectId;board.title=title;
 for(const n of board.nodes){if(!['建设方','主管部门','分管部门','使用方','招标代理','合作方',''].includes(n.type)){n.legacy_type=n.type;n.type='';}if(n.type!=='合作方'){if(n.department){n.note=(n.note?n.note+'\n':'')+'原部门：'+n.department;}delete n.department;n.person??='';n.position??='';}}
 for(const e of board.edges){e.kind??='关系线';e.chain??='';e.evidence??='';e.strength??='weak';}
 const uid=()=>crypto.randomUUID(),nodeOptions=()=>board.nodes.map(n=>`<option value="${esc(n.id)}">${esc(n.name)}</option>`).join('');
 host.innerHTML=`<section class="relationship-board"><h2>${esc(title)}</h2><p class="board-subtitle">项目决策链条</p><p class="partner-caption">点击新增节点，或双击空白处创建；双击卡片文字直接编辑，点击卡片在画布内编辑属性；滚轮缩放、按住中键拖动画布，Delete 删除选中项。从节点圆点拖向另一个节点连线，点击线设置强弱及存疑状态。</p><div class="board-toolbar"><button data-b="add" type="button">＋ 新增节点</button><select data-b="partner" aria-label="选择导入伙伴">${partners.map(p=>`<option value="${esc(p.id)}">${esc(p.id)}</option>`).join('')}</select><button data-b="import" type="button">导入合作方</button><button data-b="minus" type="button">缩小</button><button data-b="plus" type="button">放大</button><button data-b="save" type="button">保存白板</button><span data-b="status" role="status"></span></div><div class="board-layout board-direct" tabindex="0"><div class="board-scroll"><svg data-b="canvas" viewBox="0 0 1800 1200" width="1800" height="1200" aria-label="项目关系白板"></svg></div><div class="board-floating-editor" hidden><button type="button" data-b="closeEditor" aria-label="关闭编辑">×</button><form data-b="nodeForm"><h3>决策节点 / 合作方</h3><label>类型<select data-b="type"><option value="">待确认</option><option>建设方</option><option>主管部门</option><option>分管部门</option><option>使用方</option><option>招标代理</option><option>合作方</option></select></label><label>节点简称 / 合作方代号<input data-b="name" required maxlength="100"></label><div data-b="decisionFields"><label>人员<input data-b="person" placeholder="姓名不明确可填待确认"></label><label>职务<input data-b="position" placeholder="如：院长、分管副区长"></label></div><label>职责、权限与依据<textarea data-b="note" rows="3"></textarea></label><button data-b="deleteNode" type="button">删除节点</button></form><form data-b="edgeForm"><h3>链条 / 关系连线</h3><label>连线类型<select data-b="kind"><option>决策链条</option><option>合作方关系</option><option>关系线</option></select></label><label>所属决策链条<input data-b="chain" list="decisionChainNames" placeholder="如：院方决策线、区政府审批线"></label><datalist id="decisionChainNames"></datalist><label>关系说明<input data-b="label" required placeholder="如：汇报、分管、直接联系"></label><label>核验状态<select data-b="verification"><option>待验证</option><option>存疑</option><option>已验证</option></select></label><label>依据 / 存疑原因<textarea data-b="evidence" rows="2"></textarea></label><label>线型<select data-b="strength"><option value="weak">弱关联 / 待核验（虚线）</option><option value="strong">强关联（实线）</option></select></label><button data-b="deleteEdge" type="button">删除连线</button></form><p data-b="hint">点击节点编辑属性；从节点圆点拖到另一个节点即可连线。点击线编辑线型。</p></div></div></section>`;
 const $=s=>host.querySelector(`[data-b="${s}"]`),status=t=>$('status').textContent=t;
 const layout=host.querySelector('.board-layout'),viewport=host.querySelector('.board-scroll'),editor=host.querySelector('.board-floating-editor');
 function showEditor(n){editor.hidden=!n;if(!n)return;const left=n.x*zoom-viewport.scrollLeft+250*zoom,top=n.y*zoom-viewport.scrollTop;editor.style.left=Math.max(8,Math.min(layout.clientWidth-300,left))+'px';editor.style.top=Math.max(8,Math.min(220,top))+'px';}
 $('closeEditor').onclick=()=>{editor.hidden=true;layout.focus({preventScroll:true});};
 layout.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'){editor.hidden=true;return;}if(e.key==='Delete'){if(!selected&&!editingEdge)return;e.preventDefault();if(selected)$('deleteNode').click();else $('deleteEdge').click();layout.focus({preventScroll:true});}});
 function markSelection(){for(const el of host.querySelectorAll('[data-node],[data-edge]'))el.classList.toggle('board-selected',el.dataset.node===selected||el.dataset.edge===editingEdge);}
 function changed(){dirty=true;try{localStorage.setItem(key,JSON.stringify(board));status('未保存 · 本机草稿已保留');}catch(_){status('未保存 · 请保存白板');}}
 function pick(id){selected=id;showEditor(id?board.nodes.find(n=>n.id===id):null);editingEdge='';$('nodeForm').hidden=!id;$('edgeForm').hidden=true;$('hint').hidden=!!id;const n=board.nodes.find(n=>n.id===id);$('name').value=n?.name||'';$('type').value=['建设方','主管部门','分管部门','使用方','招标代理','合作方'].includes(n?.type)?n.type:'';$('note').value=n?.note||'';for(const k of ['person','position'])$(k).value=n?.[k]||'';$('decisionFields').hidden=$('type').value==='合作方';markSelection();}
 function draw(){const byId=new Map(board.nodes.map(n=>[n.id,n]));$('canvas').innerHTML=`<defs><marker id="board-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#5e7b8b"/></marker></defs>`+board.edges.map(e=>{const a=byId.get(e.from),b=byId.get(e.to);if(!a||!b)return '';const ax=a.x+120,ay=a.y+64,bx=b.x+120,by=b.y+64,dx=bx-ax,dy=by-ay,scale=1/Math.max(Math.abs(dx)/126,Math.abs(dy)/70,1);const ex=bx-dx*scale,ey=by-dy*scale;return `<g data-edge="${esc(e.id)}"><title>${esc(e.label)} · ${esc(e.verification)}</title><path d="M${ax},${ay} L${ex},${ey}" stroke="transparent" stroke-width="18" fill="none"/><path class="board-visible-edge" d="M${ax},${ay} L${ex},${ey}" stroke="${e.verification==='存疑'?'#b58136':e.kind==='决策链条'?'#355d85':'#58927b'}" stroke-width="2" ${e.strength==='strong'?'':'stroke-dasharray="7 5"'} marker-end="url(#board-arrow)"/><text x="${(ax+bx)/2}" y="${(ay+by)/2-9}" text-anchor="middle" class="board-line-label">${esc((e.chain?e.chain+' · ':'')+e.label.slice(0,20))} · ${esc(e.verification)}</text></g>`;}).join('')+board.nodes.map(n=>`<g data-node="${esc(n.id)}" transform="translate(${n.x},${n.y})" tabindex="0" role="button" aria-label="编辑${esc(n.name)}"><title>${esc(n.name)}：${esc(n.note)}</title><rect width="240" height="128" rx="9" fill="${n.type==='合作方'?'#e0eee7':'#fff'}" stroke="#8fa9b8"/><text x="12" y="23" class="board-node-type">${esc(n.type||'类型待确认')}</text><text data-edit-field="name" x="12" y="47">${esc(n.name.slice(0,16))}</text>${n.type==='合作方'?'':`<text data-edit-field="person" x="12" y="76">人员：${esc((n.person||'待确认').slice(0,15))}</text><text data-edit-field="position" x="12" y="103">职务：${esc((n.position||'待确认').slice(0,15))}</text>`}${[[0,64],[240,64],[120,0],[120,128]].map(([x,y])=>`<circle data-port="${esc(n.id)}" cx="${x}" cy="${y}" r="7" fill="#fff" stroke="#355d85" stroke-width="2"/>`).join('')}</g>`).join('');
 markSelection();host.querySelector('#decisionChainNames').innerHTML=[...new Set(board.edges.map(e=>e.chain).filter(Boolean))].map(c=>`<option value="${esc(c)}">`).join('');
 }
 let editingEdge='',drag=null,linking=null,pan=null;
 function pickEdge(id){selected='';editingEdge=id;const item=board.edges.find(e=>e.id===id);const a=board.nodes.find(n=>n.id===item.from),b=board.nodes.find(n=>n.id===item.to);showEditor({x:(a.x+b.x)/2,y:(a.y+b.y)/2});const edge=board.edges.find(e=>e.id===id);$('nodeForm').hidden=true;$('edgeForm').hidden=false;$('hint').hidden=true;for(const k of ['label','verification','kind','chain','evidence','strength'])$(k).value=edge[k]||'';markSelection();}
 function addNode(x,y){const n={id:uid(),name:'新节点',type:'建设方',person:'',position:'',note:'',x:x??80+(board.nodes.length%4)*320,y:y??80+Math.floor(board.nodes.length/4)*200};board.nodes.push(n);changed();draw();pick(n.id);$('name').focus();$('name').select();}
 $('add').onclick=()=>addNode();
 $('nodeForm').onsubmit=e=>e.preventDefault();$('edgeForm').onsubmit=e=>e.preventDefault();
 for(const k of ['name','type','person','position','note'])$(k).addEventListener('input',()=>{const n=board.nodes.find(n=>n.id===selected);if(!n)return;n[k]=$(k).value;$('decisionFields').hidden=n.type==='合作方';changed();draw();});
 for(const k of ['label','verification','kind','chain','evidence','strength'])$(k).addEventListener('input',()=>{const e=board.edges.find(e=>e.id===editingEdge);if(!e)return;e[k]=$(k).value;if(k==='verification'&&e.verification!=='已验证'){e.strength='weak';$('strength').value='weak';}changed();draw();});
 $('deleteNode').onclick=()=>{board.nodes=board.nodes.filter(n=>n.id!==selected);board.edges=board.edges.filter(e=>e.from!==selected&&e.to!==selected);changed();draw();pick('');};
 $('deleteEdge').onclick=()=>{board.edges=board.edges.filter(e=>e.id!==editingEdge);changed();draw();pick('');};
 const svg=$('canvas'),point=e=>{const r=svg.getBoundingClientRect();return {x:(e.clientX-r.left)/zoom,y:(e.clientY-r.top)/zoom};};
 svg.onpointerdown=e=>{if(e.button===1){e.preventDefault();editor.hidden=true;pan={x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};svg.setPointerCapture(e.pointerId);viewport.classList.add('board-panning');return;}if(e.button!==0)return;e.preventDefault();layout.focus({preventScroll:true});const port=e.target.closest('[data-port]');if(port){e.preventDefault();linking={from:port.dataset.port,start:point(e)};svg.setPointerCapture(e.pointerId);return;}const edge=e.target.closest('[data-edge]');if(edge){pickEdge(edge.dataset.edge);return;}const g=e.target.closest('[data-node]');if(!g){pick('');return;}const n=board.nodes.find(n=>n.id===g.dataset.node);pick(n.id);drag={id:n.id,x:e.clientX,y:e.clientY,nx:n.x,ny:n.y};};
 svg.onpointermove=e=>{if(pan){viewport.scrollLeft=pan.left+pan.x-e.clientX;viewport.scrollTop=pan.top+pan.y-e.clientY;return;}if(linking){svg.querySelector('[data-preview]')?.remove();const q=point(e);svg.insertAdjacentHTML('beforeend',`<path data-preview d="M${linking.start.x},${linking.start.y} L${q.x},${q.y}" stroke="#355d85" stroke-width="2" stroke-dasharray="7 5" pointer-events="none"/>`);return;}if(!drag)return;if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)<3)return;svg.setPointerCapture(e.pointerId);const n=board.nodes.find(n=>n.id===drag.id);n.x=Math.max(0,Math.min(1560,drag.nx+(e.clientX-drag.x)/zoom));n.y=Math.max(0,Math.min(1072,drag.ny+(e.clientY-drag.y)/zoom));draw();};
 svg.onpointerup=e=>{if(pan){pan=null;viewport.classList.remove('board-panning');return;}if(linking){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node]'),from=linking.from,to=target?.dataset.node;linking=null;svg.querySelector('[data-preview]')?.remove();if(to&&to!==from){const hasPartner=[from,to].some(id=>board.nodes.find(n=>n.id===id)?.type==='合作方');const edge={id:uid(),from,to,kind:hasPartner?'合作方关系':'决策链条',chain:'',label:'待补充关系',verification:'待验证',strength:'weak',evidence:''};board.edges.push(edge);changed();draw();pickEdge(edge.id);}return;}if(drag){changed();drag=null;layout.focus({preventScroll:true});}};
 svg.onpointercancel=()=>{pan=null;viewport.classList.remove('board-panning');linking=null;drag=null;svg.querySelector('[data-preview]')?.remove();};
 svg.onauxclick=e=>{if(e.button===1)e.preventDefault();};svg.addEventListener('mousedown',e=>{if(e.button===1)e.preventDefault();});
 svg.ondblclick=e=>{const g=e.target.closest('[data-node]');if(!g){if(!e.target.closest('[data-edge]')){const q=point(e);addNode(Math.min(q.x,1560),Math.min(q.y,1072));}return;}const n=board.nodes.find(n=>n.id===g.dataset.node),field=e.target.dataset.editField||'name';pick(n.id);editor.hidden=true;const overlay=document.createElementNS('http://www.w3.org/2000/svg','foreignObject');overlay.setAttribute('x',n.x+8);overlay.setAttribute('y',n.y+25);overlay.setAttribute('width','224');overlay.setAttribute('height','40');const input=document.createElement('input');input.value=n[field]||'';input.setAttribute('aria-label','直接编辑'+field);overlay.appendChild(input);svg.appendChild(overlay);input.onpointerdown=e=>e.stopPropagation();input.oninput=()=>{n[field]=input.value;$(field).value=input.value;changed();};input.onblur=()=>draw();input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();input.blur();}};input.focus();input.select();};
 svg.onkeydown=e=>{const g=e.target.closest('[data-node]');if(g&&e.key==='Enter'){pick(g.dataset.node);$('name').focus();}};
 function setZoom(next,clientX,clientY){const rect=viewport.getBoundingClientRect(),x=clientX-rect.left-viewport.clientLeft,y=clientY-rect.top-viewport.clientTop,worldX=(viewport.scrollLeft+x)/zoom,worldY=(viewport.scrollTop+y)/zoom;zoom=Math.max(.4,Math.min(2.5,next));svg.style.width=1800*zoom+'px';svg.style.height=1200*zoom+'px';viewport.scrollLeft=worldX*zoom-x;viewport.scrollTop=worldY*zoom-y;editor.hidden=true;}
 viewport.addEventListener('wheel',e=>{e.preventDefault();if(drag||linking||pan)return;const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?viewport.clientHeight:1);setZoom(zoom*Math.exp(-Math.max(-240,Math.min(240,delta))*.002),e.clientX,e.clientY);},{passive:false});
 for(const [id,delta] of [['minus',-.15],['plus',.15]])$(id).onclick=()=>{const rect=viewport.getBoundingClientRect();setZoom(zoom+delta,rect.left+viewport.clientWidth/2,rect.top+viewport.clientHeight/2);};
 $('import').onclick=()=>{const p=partners.find(p=>p.id===$('partner').value);if(!p)return;let n=board.nodes.find(n=>n.partner_id===p.id||(n.type==='合作方'&&n.name===p.id));if(!n){n={id:uid(),partner_id:p.id,name:p.id,type:'合作方',person:'',position:'',note:'',x:80+(board.nodes.length%4)*320,y:100+Math.floor(board.nodes.length/4)*200};board.nodes.push(n);changed();draw();}pick(n.id);};
 $('save').onclick=async()=>{$('save').disabled=true;const snapshot=JSON.parse(JSON.stringify(board));status('正在保存…');try{await save(snapshot);if(JSON.stringify(board)===JSON.stringify(snapshot)){dirty=false;localStorage.removeItem(key);status('白板已保存');}else status('已保存，另有新的修改待保存');}catch(e){status(e.message+'；当前草稿已保留');}finally{$('save').disabled=false;}};
 draw();pick('');status(dirty?'已恢复未保存的本机草稿':'拖动节点或导入伙伴开始整理');
}};
})();
