(function(){
  'use strict';
  const C=PartnerCore,A=PartnerAPI,$=id=>document.getElementById(id),esc=C.esc;
  const query=new URLSearchParams(location.search);
  let data=null,sha='',config=A.settings(),projects=[],versions={},selected=query.get('partner')||'',project=query.get('project')||'',mode=project?'projects':'people',loading=false;
  const stages=['线索获取','前期信息提供','引荐对接','关系协调','团队分工','招标准备与参与','履约协调'];
  $('partnerOwner').value=config.owner;$('partnerRepo').value=config.repo;$('partnerBranch').value=config.branch;$('partnerToken').value=config.token;
  function status(text){$('partnerStatus').textContent=text;}
  function setMode(next){mode=next;$('peopleView').hidden=mode!=='people';$('projectsView').hidden=mode!=='projects';$('showPeople').setAttribute('aria-pressed',String(mode==='people'));$('showProjects').setAttribute('aria-pressed',String(mode==='projects'));updateUrl();}
  function updateUrl(){const url=new URL(location.href);url.searchParams.delete('partner');url.searchParams.delete('project');if(mode==='projects'&&project)url.searchParams.set('project',project);else if(selected)url.searchParams.set('partner',selected);history.replaceState(null,'',url);}
  function currentConfig(){const previous=A.settings();const next={...previous,owner:$('partnerOwner').value.trim(),repo:$('partnerRepo').value.trim(),branch:$('partnerBranch').value.trim()||'main',token:$('partnerToken').value.trim()};if(!next.owner||!next.repo)throw Error('请填写仓库连接设置');return next;}
  function saveSettings(){let common={};try{common=JSON.parse(localStorage.getItem('bd-weekly-github-settings')||'{}');}catch(_){}localStorage.setItem('bd-weekly-github-settings',JSON.stringify({...common,token:config.token}));localStorage.setItem('bd-partner-settings',JSON.stringify({owner:config.owner,repo:config.repo,branch:config.branch}));}
  function sourceUrl(p){return 'https://github.com/'+encodeURIComponent(config.owner)+'/'+encodeURIComponent(config.repo)+'/blob/'+encodeURIComponent(config.branch)+'/'+encodeURIComponent(p.source_file);}
  function stale(p){return !versions[p.source_file]||versions[p.source_file]!==p.source_sha;}
  function warning(p){return stale(p)?'<div class="partner-warning">档案正文已变化或版本无法核对。以下评价与关系图为上次整理结果，请先查看最新正文，再让建档助手更新可视化索引。</div>':'';}
  function renderList(){if(!data)return;const term=$('partnerSearch').value.trim().toLowerCase();const list=data.partners.filter(p=>(p.id+' '+(p.city||'')).toLowerCase().includes(term));$('partnerList').innerHTML=[...new Set(list.map(p=>p.city||'待确认'))].map(city=>'<h2 class="partner-city-group">'+esc(city)+'</h2>'+list.filter(p=>(p.city||'待确认')===city).map(p=>`<button class="partner-select" type="button" data-partner="${esc(p.id)}" aria-pressed="${p.id===selected}"><strong>${esc(p.id)}</strong><span>合作项目 ${C.projectCount(p)}</span></button>`).join('')).join('');}
  function platformText(p,l){const type=l?.platform_type??p.role_platform?.type??'';const name=l?.platform_name??p.role_platform?.name??'';return type?(type+(type==='背靠平台'&&name?' · '+name:'')):'待确认';}
  function capabilityTable(p){const groups=['政府','城投平台','民营企业','其他机构'];return groups.map(category=>{const rows=(p.capability_relations||[]).filter(r=>r.category===category);if(!rows.length&&category==='其他机构')return '';return `<section class="capability-group"><h4>${category}</h4>${rows.length?`<div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>关系对象</th><th>关系距离</th><th>核验状态</th><th>依据</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.to)}</td><td><span class="relationship-distance">${esc(r.distance)}关系</span></td><td>${esc(r.verification)}</td><td>${esc(r.label)}${r.from!==p.id?'<br><small>关系主体：'+esc(r.from)+'</small>':''}</td></tr>`).join('')}</tbody></table></div>`:'<p class="partner-caption">暂无已记录关系</p>'}</section>`;}).join('');}
  function fulfilled(p){const records=p.fulfilled_projects||[];return records.length?`<div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>已履约项目</th><th>完成事项</th><th>完成时间</th><th>结果依据</th></tr></thead><tbody>${records.map(r=>`<tr><td>${esc(r.project_name)}</td><td>${esc(r.delivered)}</td><td>${esc(r.completed_at||'未记录')}</td><td>${esc(r.evidence)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="partner-empty compact-empty">暂无已完成履约的项目记录</p>';}
  function information(p){const metrics=C.informationStats(p.information_records||[]);return `<div class="information-metrics"><section><h4>准确度</h4><strong>${metrics.accuracyTotal?metrics.accurate+'/'+metrics.accuracyTotal:'待核验'}</strong><p>${metrics.accuracyTotal?'准确条数 / 已核验条数':'暂无已核验信息样本'}</p></section><section><h4>及时度</h4><strong>${metrics.timingTotal?metrics.timely+'/'+metrics.timingTotal:'待核验'}</strong><p>${metrics.timingTotal?'及时条数 / 有时效依据条数':'需记录提供时间与决策节点'}</p></section><section><h4>主动分享</h4><strong>${metrics.sharingTotal?metrics.proactive+'/'+metrics.sharingTotal:'待记录'}</strong><p>${metrics.sharingTotal?'主动提供 / 已知分享方式条数':'区分主动提供与询问后回复'}</p></section></div><details class="information-method"><summary>信息如何记录与考核</summary><p>逐条记录原话、提供时间、来源、决策节点、是否主动提供、核验结果、核验时间和依据。准确度只统计已核验信息；部分准确单列，不直接折算。及时度看信息是否赶在本项目决策节点前提供。主动分享按明确记录的分享方式统计。</p><p>未来计划与预测单独记录，不直接按事实准确率计算。无样本显示待核验，不记为零分。</p></details>`;}
  function paths(p,projectId){const relations=(p.relations||[]).filter(r=>!projectId||(r.project_ids||[]).includes(projectId));return relations.map(r=>`<div class="relation-path"><span class="relation-node">${esc(r.from)}</span><span class="relation-edge ${r.evidence==='claim'?'claim':''}">${esc(r.label)}<small>${esc(r.distance)} · ${r.evidence==='claim'?'自述 / 转述待核':r.evidence==='observed'?'用户亲历':'用户陈述'}</small></span><span class="relation-node">${esc(r.to)}</span></div>`).join('')||'<p class="partner-caption">该项目尚未整理关系路径，关联不代表这些资源已用于此项目。</p>';}
  function renderDetail(){if(!data)return;const p=data.partners.find(p=>p.id===selected)||data.partners[0];if(!p)return;selected=p.id;const count=C.counts(p);
    $('partnerDetail').innerHTML=`<header class="partner-detail-header"><div><h2>${esc(p.name)}</h2><span class="partner-role">${esc(p.city||'待确认')}</span></div><div class="profile-actions"><button type="button" data-profile="basic">编辑基本资料</button><button type="button" data-add="${esc(p.id)}">关联项目</button></div></header>${warning(p)}
    <section class="partner-section"><h3>01 · 项目接触与转化</h3><div class="partner-metrics">${C.STAGES.map((label,i)=>`<div class="partner-metric"><b>${count[i]}</b><span>${label}</span></div>`).join('')}</div><div class="partner-table-wrap"><table class="partner-table"><thead><tr><th>关联项目</th><th>合作阶段</th><th>角色平台</th><th>操作</th></tr></thead><tbody>${p.project_links.map(l=>`<tr><td><a href="${esc(C.href('ledger.html',{project:l.project_id}))}">${esc(projects.find(x=>x.project_id===l.project_id)?.['项目名称']||l.project_name)} ↗</a></td><td>${esc(C.stageFor(l))}</td><td>${esc(platformText(p,l))}</td><td><button data-edit="${esc(l.project_id)}" type="button">编辑</button> <a href="${esc(C.href('partners.html',{project:l.project_id}))}">项目关系</a></td></tr>`).join('')||'<tr><td colspan="4">暂无项目关联</td></tr>'}</tbody></table></div><p class="partner-caption">同一项目只计一次；合作阶段按当前状态分类。合作失败不等于履约失败。</p></section>
    <section class="partner-section"><h3>02 · 关系能力 <button type="button" class="section-edit" data-profile="relations">编辑</button></h3>${capabilityTable(p)}</section>
    <section class="partner-section"><h3>03 · 履约能力 <button type="button" class="section-edit" data-profile="fulfilled">编辑</button></h3>${fulfilled(p)}</section>
    <section class="partner-section organization-unchanged"><h3>04 · 组织推进能力 <button type="button" class="section-edit" data-profile="organization">编辑</button></h3><p>${esc(p.dimensions[2].text)}</p><div class="partner-stage-track">${stages.map(s=>`<span class="${p.coverage.includes(s)?'recorded':''}">${esc(s)} · ${p.coverage.includes(s)?'有行为记录':'暂无记录'}</span>`).join('')}</div><p class="partner-caption">有行为记录不等于能够独立完成该环节或保证项目结果。</p></section>
    <section class="partner-section"><h3>05 · 信息质量 <button type="button" class="section-edit" data-profile="information">编辑</button></h3>${information(p)}</section>
    <details class="partner-secondary"><summary>补充评价：合作协同与商务条件</summary><h3>06 · 合作协同 <button type="button" class="section-edit" data-profile="collaboration">编辑</button></h3><p>${esc(p.dimensions[4].text)}</p><h3>07 · 商务匹配 <button type="button" class="section-edit" data-profile="business">编辑</button></h3><p>${esc(p.dimensions[5].text)}</p></details>
    <details id="sourceDetails"><summary>查看最新档案正文</summary><p><a href="${esc(sourceUrl(p))}" target="_blank" rel="noopener">在 GitHub 查看主档 ↗</a></p><p id="sourceVersion" class="partner-caption"></p><pre id="sourceText" class="partner-source">展开后读取正文。</pre></details>`;
    $('sourceDetails').addEventListener('toggle',async()=>{if(!$('sourceDetails')?.open)return;const id=p.id;try{const r=await A.read(config,p.source_file);if(selected!==id)return;$('sourceText').textContent=r.text.replace(/WPW/g,'PWW').replace(/FLX/g,'FXL');$('sourceVersion').textContent='本次正文版本 '+r.sha.slice(0,10)+' · '+new Date().toLocaleString('zh-CN');}catch(e){if(selected===id)$('sourceText').textContent=e.message;}});
    renderList();updateUrl();
  }
  function allProjects(){const combined=new Map(projects.map(p=>[p.project_id,{id:p.project_id,name:p['项目名称']||p.project_id}]));for(const p of data?.partners||[])for(const l of p.project_links)if(!combined.has(l.project_id))combined.set(l.project_id,{id:l.project_id,name:l.project_name+'（台账未返回）'});return [...combined.values()];}
  function fillProjects(){const list=allProjects();$('relationProject').innerHTML='<option value="">选择项目查看关系</option>'+list.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(project&&!list.some(p=>p.id===project)){status('指定项目在当前台账中不存在，请重新选择。');project='';}$('relationProject').value=project;}
  function renderProject(){if(!data)return;$('backToLedger').href=C.href('ledger.html',project?{project}:{});if(!project){$('projectRelations').innerHTML='<p class="partner-empty">选择一个项目，查看关联伙伴的关系图与合作对比。</p>';return;}
    const rows=C.forProject(data,project),title=allProjects().find(p=>p.id===project)?.name||project;
    $('projectRelations').innerHTML=`<div class="project-root">${esc(title)}</div><div id="projectBoard"></div>${rows.length?`${comparisonTable(rows)}<h2>项目关系图</h2><div class="project-branches">${rows.map(({partner:p,link:l})=>`<article class="project-branch"><header><strong><a href="${esc(C.href('partners.html',{partner:p.id}))}">${esc(p.name)} ↗</a></strong><span>${esc(C.stageFor(l))} · ${esc(platformText(p,l))}</span></header>${warning(p)}${paths(p,project)}<p>下一步验证：${esc(l.next||'尚未填写')}</p></article>`).join('')}</div>`:'<p class="partner-empty">此项目还没有关联伙伴。点击“关联伙伴”建立关系。</p>'}`;
    const boardProject=project;
    PartnerBoard.mount($('projectBoard'),{projectId:boardProject,title,partners:rows.map(r=>r.partner),stored:data.project_boards?.[boardProject],save:async board=>{const next=JSON.parse(JSON.stringify(data));next.project_boards={...next.project_boards,[boardProject]:board};next.updated_at=new Date().toISOString();const result=await A.saveIndex(config,next,sha);data=next;sha=result.sha;}});
    updateUrl();
  }
  async function load(){if(loading)return;loading=true;$('refreshPartners').disabled=true;status('正在读取伙伴档案与项目台账…');try{config=currentConfig();saveSettings();const index=await A.readIndex(config);data=index.data;sha=index.sha;const results=await Promise.allSettled([A.sourceVersions(config),A.read({...config,owner:config.ledgerOwner,repo:config.ledgerRepo,branch:config.ledgerBranch},'ledger/market_workbench_snapshot.json')]);versions=results[0].status==='fulfilled'?results[0].value:{};projects=[];let note='';if(results[1].status==='fulfilled'){const snapshot=JSON.parse(results[1].value.text);projects=(snapshot.projects||[]).filter(p=>!['已删除','已合并','已归档'].includes(p['记录状态']));}else note='；项目台账读取失败，保留已存关联，新增关联暂不可用。'+results[1].reason.message;fillProjects();renderDetail();renderProject();setMode(mode);status(`已读取 ${data.partners.length} 位伙伴 · ${projects.length} 个台账项目 · 关联版本 ${sha.slice(0,8)} · ${new Date().toLocaleTimeString('zh-CN')}${note}`);$('partnerSettings').open=false;}catch(e){status(e.message);$('partnerSettings').open=true;}finally{loading=false;$('refreshPartners').disabled=false;}}
  function setFormLink(){const p=data.partners.find(p=>p.id===$('linkPartner').value);const l=p?.project_links.find(l=>l.project_id===$('linkProject').value);$('linkStage').value=l?C.stageFor(l):'合作意向';$('linkPlatformType').value=l?.platform_type??p?.role_platform?.type??'';$('linkPlatformName').value=l?.platform_name??p?.role_platform?.name??'';$('linkEvidence').value=l?.evidence||'';$('linkNext').value=l?.next||'';}
  function openLink(partnerId,projectId){if(!data)return;if(!projects.length){status('请先成功读取项目台账，再建立或修改关联。');return;}$('linkPartner').innerHTML=data.partners.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');$('linkProject').innerHTML=projects.map(p=>`<option value="${esc(p.project_id)}">${esc(p['项目名称'])}</option>`).join('');if(partnerId)$('linkPartner').value=partnerId;if(projectId)$('linkProject').value=projectId;setFormLink();$('linkResult').textContent='';$('linkDialog').showModal();}
  $('refreshPartners').addEventListener('click',load);$('showPeople').addEventListener('click',()=>setMode('people'));$('showProjects').addEventListener('click',()=>setMode('projects'));$('partnerSearch').addEventListener('input',renderList);
  $('partnerList').addEventListener('click',e=>{const button=e.target.closest('[data-partner]');if(button){selected=button.dataset.partner;renderDetail();}});
  $('partnerDetail').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),edit=e.target.closest('[data-edit]');if(add)openLink(add.dataset.add,project);if(edit)openLink(selected,edit.dataset.edit);});
  $('relationProject').addEventListener('change',()=>{project=$('relationProject').value;renderProject();});$('addProjectPartner').addEventListener('click',()=>openLink('',project));$('closeLink').addEventListener('click',()=>$('linkDialog').close());$('linkPartner').addEventListener('change',setFormLink);$('linkProject').addEventListener('change',setFormLink);
  $('linkForm').addEventListener('submit',async e=>{e.preventDefault();$('saveLink').disabled=true;try{const id=$('linkProject').value,p=projects.find(p=>p.project_id===id);if(!p)throw Error('请选择有效台账项目');const next=C.upsertLink(data,$('linkPartner').value,{project_id:id,project_name:p['项目名称'],cooperation_stage:$('linkStage').value,status:$('linkStage').value,platform_type:$('linkPlatformType').value,platform_name:$('linkPlatformName').value.trim(),evidence:$('linkEvidence').value.trim(),next:$('linkNext').value.trim()});const saved=await A.saveIndex(config,next,sha);data=next;sha=saved.sha;fillProjects();renderDetail();renderProject();$('linkDialog').close();status('关联已保存到 GitHub · 提交 '+saved.commit.slice(0,8)+'。台账刷新后可查看伙伴入口。');}catch(err){$('linkResult').textContent=err.message;}finally{$('saveLink').disabled=false;}});
  function relationLevel(r){if(r.level)return r.level;if(/副区长|区书记|区委书记/.test(r.to))return '区级政府领导';if(/市委书记|副市长|市长/.test(r.to))return '市级政府领导';if(r.category==='政府')return '政府职能部门';if(['城投平台','民营企业','其他机构'].includes(r.category))return '实操平台';return '其他';}
  function comparisonTable(rows){
    const relationCell=(p,level)=>{const records=(p.capability_relations||[]).filter(r=>(r.project_ids||[]).includes(project)&&relationLevel(r)===level);return records.length?records.map(r=>`<div class="compare-relation"><strong>${esc(r.to)}</strong><br>${esc(r.from)} → ${esc(r.distance)}关系 · ${esc(r.verification||'待验证')}<br><small>${esc(r.label)}</small></div>`).join(''):'<span class="partner-caption">待确认</span>';};
    const feeCell=l=>{const c=l.comparison||{};return `<strong>${c.fee_amount?esc(c.fee_amount)+' 万元':'金额待确认'}${c.fee_percent?' / '+esc(c.fee_percent)+'%':''}</strong><br><small>计费口径：${esc(c.fee_basis||'待确认')}<br>承担工作：${esc(c.work_scope||'待确认')}<br>商务说明：${esc(c.fee_note||'待确认')}</small>`;};
    const historyCell=(p,key)=>{const h=p.cooperation_history||{};return esc(h[key]||'待确认')+'<br><small>'+esc(h[key+'_note']||'尚无明确记录')+'</small>';};
    const dimensions=[...['实操平台','区级政府领导','市级政府领导','政府职能部门'].map(level=>[level,({partner:p})=>relationCell(p,level)]),['留给浙大院的设计费',({link:l})=>feeCell(l)],['以往成功合作经历',({partner:p})=>historyCell(p,'success')],['长期合作方',({partner:p})=>historyCell(p,'long_term')],['当前合作阶段',({link:l})=>esc(C.stageFor(l))]];
    return `<section class="project-comparison"><h2>合作关系对比</h2><p class="partner-caption">按当前项目对比，关系格内标明主体、直接／间接及核验状态。政府职能部门单列，避免将局处领导混同为市、区级政府领导。成功经历指与浙大院／我方共同合作的成功项目；未记录不等于没有。</p><div class="partner-table-wrap"><table class="partner-table comparison-matrix"><thead><tr><th scope="col">对比项</th>${rows.map(({partner:p})=>`<th scope="col"><a href="${esc(C.href('partners.html',{partner:p.id}))}">${esc(p.id)}</a> <button type="button" data-compare="${esc(p.id)}">编辑对比</button>${stale(p)?'<br>评价待同步':''}</th>`).join('')}</tr></thead><tbody>${dimensions.map(([label,cell])=>`<tr><th scope="row">${label}</th>${rows.map(row=>'<td>'+cell(row)+'</td>').join('')}</tr>`).join('')}</tbody></table></div><p class="partner-caption">费用比较需统一含税口径、总设计费基数和承担的工作范围；留存设计费不等于利润。关系层级不自动代表本项目的决策权限。</p></section>`;
  }
  const profileSchemas={
    comparison:{title:'项目合作对比',fields:[['fee_amount','留给浙大院的设计费（万元）','number'],['fee_percent','占总设计费比例（%）','number'],['fee_basis','费用口径（含税情况、总设计费基数）','textarea'],['work_scope','浙大院承担的工作范围','textarea'],['fee_note','商务诉求、报价依据与时间','textarea'],['success','与我方以往成功合作',['待确认','有','无']],['success_note','成功合作项目与结果依据','textarea'],['long_term','是否我方长期合作方',['待确认','是','否']],['long_term_note','合作起始时间、持续情况及依据','textarea']]},
    basic:{title:'基本资料',fields:[['city','城市','text',true],['type','角色平台',['','个人','背靠平台']],['name','平台名称']]},
    relations:{title:'关系能力',key:'capability_relations',fields:[['category','关系类别',['政府','城投平台','民营企业','其他机构']],['from','关系主体','text',true],['to','关系对象','text',true],['level','对接层级',['','实操平台','区级政府领导','市级政府领导','政府职能部门','其他']],['distance','关系距离',['直接','间接']],['verification','核验状态',['待验证','已验证']],['evidence','依据来源',['claim','user','observed']],['label','关系说明与依据','textarea',true],['project_ids','关联项目','projects']]},
    fulfilled:{title:'已履约项目',key:'fulfilled_projects',fields:[['project_id','项目','project',true],['delivered','已完成事项','textarea',true],['completed_at','完成时间','date',true],['evidence','结果依据','textarea',true]]},
    organization:{title:'组织推进能力',fields:[['text','能力记录','textarea'],['coverage','已有行为记录','coverage']]},
    information:{title:'信息质量记录',key:'information_records',fields:[['content','信息原话','textarea',true],['source','信息来源'],['project_id','关联项目','project'],['kind','信息性质',['事实','预测']],['provided_at','提供日期','date',true],['decision_deadline','决策节点日期','date'],['sharing','分享方式',['','主动提供','询问后回复']],['verification_status','核验状态',['待验证','已验证']],['accuracy','准确度',['','准确','部分准确','不准确']],['timely','是否及时',['','true','false']],['verified_at','核验日期','date'],['evidence','核验依据','textarea']]},
    collaboration:{title:'合作协同',fields:[['text','协同表现与依据','textarea']]},
    business:{title:'商务匹配',fields:[['text','商务条件与依据','textarea']]}
  };
  let editKind='',editPartner='',editRows=[];
  function recordFields(row,i){return `<fieldset data-record="${i}"><legend>${profileSchemas[editKind].key?'记录 '+(i+1):'档案内容'}</legend>${profileSchemas[editKind].fields.map(([key,label,type,required])=>{const value=row[key]??'';let control;const attrs=`data-field="${key}" ${required?'required':''}`;if(Array.isArray(type)){const labels={claim:'自述 / 转述',user:'用户陈述',observed:'用户亲历',true:'及时',false:'不及时'};control=`<select ${attrs}>${type.map(v=>`<option value="${esc(v)}" ${String(value)===v?'selected':''}>${esc(labels[v]||v||'待确认')}</option>`).join('')}</select>`;}else if(type==='projects'||type==='coverage'){const choices=type==='coverage'?stages.map(s=>({id:s,name:s})):allProjects();control=choices.map(c=>`<label class="profile-check"><input type="checkbox" data-field="${key}" value="${esc(c.id)}" ${(Array.isArray(value)?value:[]).includes(c.id)?'checked':''}>${esc(c.name)}</label>`).join('');}else if(type==='project'){control=`<select ${attrs}><option value="">请选择项目</option>${allProjects().map(p=>`<option value="${esc(p.id)}" ${value===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select>`;}else if(type==='textarea'){control=`<textarea ${attrs} rows="3">${esc(value)}</textarea>`;}else control=`<input ${attrs} type="${type||'text'}" ${type==='number'?'min="0" step="any"'+(key==='fee_percent'?' max="100"':''):''} value="${esc(value)}">`;return `<div class="profile-field">${type==='projects'||type==='coverage'?`<div>${label}${control}</div>`:`<label>${label}${control}</label>`}</div>`;}).join('')}${profileSchemas[editKind].key?'<button type="button" data-remove-record="'+i+'">移除此记录</button>':''}</fieldset>`;}
  function collectRows(){return [...$('profileFields').querySelectorAll('[data-record]')].map((node,i)=>{const row={...editRows[i]};for(const [key,,type] of profileSchemas[editKind].fields){if(type==='projects'||type==='coverage')row[key]=[...node.querySelectorAll(`[data-field="${key}"]:checked`)].map(x=>x.value);else{const value=node.querySelector(`[data-field="${key}"]`).value.trim();row[key]=key==='timely'?(value===''?null:value==='true'):value;}}return row;});}
  function drawEditor(){$('profileFields').innerHTML=editRows.map(recordFields).join('')||'<p>暂无记录，点击新增记录开始填写。</p>';}
  function openProfile(kind,partnerId){const p=data.partners.find(p=>p.id===(partnerId||selected)),schema=profileSchemas[kind];editKind=kind;editPartner=p.id;let rows;if(kind==='comparison')rows=[{...(p.project_links.find(l=>l.project_id===project)?.comparison||{}),...p.cooperation_history}];else if(schema.key)rows=p[schema.key]||[];else if(kind==='basic')rows=[{city:p.city,...p.role_platform}];else rows=[{text:p.dimensions[{organization:2,collaboration:4,business:5}[kind]].text,coverage:p.coverage}];editRows=JSON.parse(JSON.stringify(rows));$('profileTitle').textContent=p.id+' · '+schema.title+(kind==='comparison'?' · '+(allProjects().find(x=>x.id===project)?.name||''):'');$('profileResult').textContent='';$('addProfileRecord').hidden=!schema.key;drawEditor();$('profileDialog').showModal();}
  $('projectRelations').addEventListener('click',e=>{const button=e.target.closest('[data-compare]');if(button)openProfile('comparison',button.dataset.compare);});
  $('partnerDetail').addEventListener('click',e=>{const button=e.target.closest('[data-profile]');if(button)openProfile(button.dataset.profile);});
  $('closeProfile').addEventListener('click',()=>$('profileDialog').close());
  $('addProfileRecord').addEventListener('click',()=>{editRows=collectRows();editRows.push(editKind==='relations'?{from:editPartner,category:'政府',distance:'直接',verification:'待验证',evidence:'claim',project_ids:[]}:editKind==='information'?{kind:'事实',verification_status:'待验证'}:{});drawEditor();});
  $('profileFields').addEventListener('click',e=>{const button=e.target.closest('[data-remove-record]');if(button){editRows=collectRows();editRows.splice(Number(button.dataset.removeRecord),1);drawEditor();}});
  $('profileForm').addEventListener('submit',async e=>{e.preventDefault();$('saveProfile').disabled=true;try{const rows=collectRows(),next=JSON.parse(JSON.stringify(data)),p=next.partners.find(p=>p.id===editPartner),schema=profileSchemas[editKind];if(editKind==='information')for(const r of rows){if(r.verification_status==='已验证'&&(!r.evidence||!r.verified_at))throw Error('已验证的信息请填写核验日期与依据');if(typeof r.timely==='boolean'&&(!r.decision_deadline||!r.evidence))throw Error('判断及时度请填写决策节点与依据');}
    if(editKind==='comparison'){const r=rows[0],l=p.project_links.find(x=>x.project_id===project);if(!l)throw Error('项目关联不存在，请刷新后重试');if(r.success==='有'&&!r.success_note)throw Error('请填写成功合作项目与结果依据');if(r.long_term==='是'&&!r.long_term_note)throw Error('请填写长期合作的依据');l.comparison={fee_amount:r.fee_amount,fee_percent:r.fee_percent,fee_basis:r.fee_basis,work_scope:r.work_scope,fee_note:r.fee_note};p.cooperation_history={success:r.success,success_note:r.success_note,long_term:r.long_term,long_term_note:r.long_term_note};}else if(schema.key){if(editKind==='relations'){const old=p.capability_relations||[];p.relations=(p.relations||[]).filter(r=>!old.some(o=>o.from===r.from&&o.to===r.to)).concat(rows.map(r=>({...r})));}if(editKind==='fulfilled')for(const r of rows)r.project_name=allProjects().find(x=>x.id===r.project_id)?.name||r.project_name;p[schema.key]=rows;}else if(editKind==='basic'){p.city=rows[0].city;p.role_platform={type:rows[0].type,name:rows[0].name};}else{p.dimensions[{organization:2,collaboration:4,business:5}[editKind]].text=rows[0].text;if(editKind==='organization')p.coverage=rows[0].coverage;}
    p.manually_updated_at=new Date().toISOString();next.updated_at=p.manually_updated_at;C.validate(next);const result=await A.saveIndex(config,next,sha);data=next;sha=result.sha;renderDetail();renderProject();$('profileDialog').close();status(editPartner+' · '+schema.title+'已保存'+(window.PARTNER_LOCAL_PREVIEW?'到本地':'到 GitHub'));}catch(error){$('profileResult').textContent=error.message;}finally{$('saveProfile').disabled=false;}});

  setMode(mode);if(config.token)load();else $('partnerSettings').open=true;
})();
